import React, { useRef } from 'react';
import { ShieldCheck, Download, Copy, Check, QrCode, AlertTriangle, Syringe, Heart, Calendar, Award } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { getVaccineStatus } from '../utils/vaccineUtils';

export default function PetPassportCard({ pet, onTabChange }) {
  const [copied, setCopied] = React.useState(false);

  if (!pet) return null;

  const handleCopyMicrochip = () => {
    navigator.clipboard.writeText(pet.microchipId);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportPDF = () => {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    // Outer passport border styling
    doc.setFillColor(15, 23, 42); // Dark slate
    doc.rect(0, 0, 210, 297, 'F');

    // Header Banner
    doc.setFillColor(79, 70, 229); // Indigo
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('OFFICIAL INTERNATIONAL PET PASSPORT', 105, 22, { align: 'center' });
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Global Pet Travel Compliance & Health Record', 105, 30, { align: 'center' });

    // Pet Info Box
    doc.setFillColor(30, 41, 59);
    doc.roundedRect(15, 50, 180, 75, 4, 4, 'F');

    doc.setFontSize(18);
    doc.setTextColor(245, 158, 11);
    doc.text(`PASSPORT NO: ${pet.passportNumber || 'PET-PASS-001'}`, 25, 65);

    doc.setFontSize(11);
    doc.setTextColor(255, 255, 255);
    doc.text(`Pet Name: ${pet.name}`, 25, 78);
    doc.text(`Species: ${pet.species}`, 25, 86);
    doc.text(`Breed: ${pet.breed}`, 25, 94);
    doc.text(`Sex / Neutered: ${pet.sex}`, 25, 102);
    doc.text(`Microchip ID: ${pet.microchipId}`, 25, 110);

    doc.text(`Weight: ${pet.weightKg} kg`, 110, 78);
    doc.text(`Color: ${pet.color}`, 110, 86);
    doc.text(`Date of Birth: ${pet.dob}`, 110, 94);
    doc.text(`Microchip Date: ${pet.microchipDate}`, 110, 102);
    doc.text(`Route: ${pet.originCountry} --> ${pet.destinationCountry}`, 110, 110);

    // Vet Info Box
    doc.setFillColor(30, 41, 59);
    doc.roundedRect(15, 135, 180, 45, 4, 4, 'F');

    doc.setFontSize(14);
    doc.setTextColor(99, 102, 241);
    doc.text('LICENSED VETERINARIAN OF RECORD', 25, 148);
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.text(`Name: ${pet.veterinarian?.name || 'N/A'}`, 25, 158);
    doc.text(`Clinic: ${pet.veterinarian?.clinic || 'N/A'}`, 25, 166);
    doc.text(`Phone: ${pet.veterinarian?.phone || 'N/A'}`, 110, 158);
    doc.text(`License No: ${pet.veterinarian?.license || 'N/A'}`, 110, 166);

    // Vaccination Table Header
    doc.setFillColor(79, 70, 229);
    doc.rect(15, 190, 180, 10, 'F');
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.text('VACCINE / TEST NAME', 20, 196);
    doc.text('ADMINISTERED', 85, 196);
    doc.text('EXPIRY DATE', 130, 196);
    doc.text('STATUS', 170, 196);

    // Vaccination Rows
    let y = 208;
    pet.vaccinations.forEach(v => {
      const { status } = getVaccineStatus(v);
      doc.setFillColor(30, 41, 59);
      doc.rect(15, y - 6, 180, 12, 'F');
      doc.setFontSize(9);
      doc.setTextColor(255, 255, 255);
      doc.text(v.name.substring(0, 32), 20, y);
      doc.text(v.dateAdministered, 85, y);
      doc.text(v.dateExpires, 130, y);
      doc.text(status.toUpperCase(), 170, y);
      y += 15;
    });

    // Footer Watermark & Date
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`Generated by Pet Passport System on ${new Date().toLocaleDateString()} | Digital Pet Health & Travel Summary`, 105, 288, { align: 'center' });

    doc.save(`${pet.name}_Pet_Passport.pdf`);
  };

  const rabiesVaccine = pet.vaccinations.find(v => v.name.toLowerCase().includes('rabies'));
  const rabiesStatus = rabiesVaccine ? getVaccineStatus(rabiesVaccine) : null;
  const titreTest = pet.vaccinations.find(v => v.name.toLowerCase().includes('titre') || v.name.toLowerCase().includes('favn'));

  return (
    <div style={{ padding: '24px 0' }}>
      {/* Top Banner Action */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
        flexWrap: 'wrap',
        gap: 16
      }}>
        <div>
          <h2 style={{ fontSize: '1.6rem', color: 'var(--text-primary)', margin: 0 }}>
            {pet.name}'s Digital Passport
          </h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.88rem', margin: '4px 0 0 0' }}>
            Official travel certificate & verified health passport card
          </p>
        </div>

        <button onClick={handleExportPDF} className="btn-primary">
          <Download size={18} /> Download Printable PDF Passport
        </button>
      </div>

      {/* Main Passport Card */}
      <div className="glass-panel" style={{
        position: 'relative',
        overflow: 'hidden',
        border: '1px solid rgba(99, 102, 241, 0.4)',
        boxShadow: '0 20px 40px rgba(0,0,0,0.3)',
        padding: 0
      }}>
        {/* Card Header Strip */}
        <div style={{
          background: 'var(--color-brand-gradient)',
          padding: '16px 24px',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          color: '#fff'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <Award size={24} color="#F59E0B" />
            <div>
              <div style={{ fontWeight: 800, fontSize: '1.1rem', letterSpacing: '0.05em' }}>
                PASSPORT NO: {pet.passportNumber}
              </div>
              <div style={{ fontSize: '0.75rem', opacity: 0.9 }}>
                Official Microchip Verified Identity Pass
              </div>
            </div>
          </div>
          <span className="badge badge-valid" style={{ background: '#fff', color: '#4F46E5', fontWeight: 800 }}>
            VERIFIED ACTIVE
          </span>
        </div>

        {/* Card Body */}
        <div style={{ padding: 24, display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 24 }}>
          {/* Column 1: Photo & Microchip ID */}
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center', gap: 16 }}>
            <div style={{
              width: 140,
              height: 140,
              borderRadius: 24,
              overflow: 'hidden',
              border: '4px solid var(--color-brand-primary)',
              boxShadow: 'var(--shadow-lg)'
            }}>
              <img 
                src={pet.photoUrl} 
                alt={pet.name} 
                style={{ width: '100%', height: '100%', objectFit: 'cover' }}
              />
            </div>
            
            <div>
              <h3 style={{ fontSize: '1.5rem', color: 'var(--text-primary)', margin: 0 }}>{pet.name}</h3>
              <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', margin: '2px 0 0 0' }}>
                {pet.breed} • {pet.species}
              </p>
            </div>

            {/* Microchip Display Box */}
            <div style={{
              width: '100%',
              background: 'var(--bg-surface-elevated)',
              padding: '12px 16px',
              borderRadius: 14,
              border: '1px solid var(--border-color)',
              textAlign: 'left'
            }}>
              <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', fontWeight: 700 }}>
                ISO 11784 / 11785 Microchip ID
              </div>
              <div style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                marginTop: 6,
                fontFamily: 'monospace',
                fontWeight: 700,
                fontSize: '1.05rem',
                color: 'var(--color-brand-accent)'
              }}>
                <span>{pet.microchipId}</span>
                <button
                  onClick={handleCopyMicrochip}
                  style={{
                    background: 'transparent',
                    border: 'none',
                    color: copied ? 'var(--color-emerald)' : 'var(--text-secondary)',
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    gap: 4
                  }}
                  title="Copy Microchip ID"
                >
                  {copied ? <Check size={16} /> : <Copy size={16} />}
                </button>
              </div>
            </div>
          </div>

          {/* Column 2: Health & Travel Specifications */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
            <div style={{
              display: 'grid',
              gridTemplateColumns: '1fr 1fr',
              gap: 12,
              background: 'var(--bg-surface-elevated)',
              padding: 16,
              borderRadius: 16,
              border: '1px solid var(--border-color)'
            }}>
              <div>
                <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', display: 'block' }}>SEX / STATUS</span>
                <strong style={{ fontSize: '0.92rem', color: 'var(--text-primary)' }}>{pet.sex}</strong>
              </div>
              <div>
                <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', display: 'block' }}>WEIGHT</span>
                <strong style={{ fontSize: '0.92rem', color: 'var(--text-primary)' }}>{pet.weightKg} kg</strong>
              </div>
              <div>
                <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', display: 'block' }}>DATE OF BIRTH</span>
                <strong style={{ fontSize: '0.92rem', color: 'var(--text-primary)' }}>{pet.dob}</strong>
              </div>
              <div>
                <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', display: 'block' }}>COLOR / MARKS</span>
                <strong style={{ fontSize: '0.92rem', color: 'var(--text-primary)' }}>{pet.color}</strong>
              </div>
            </div>

            {/* Travel Route Info */}
            <div style={{
              background: 'rgba(99, 102, 241, 0.1)',
              border: '1px solid rgba(99, 102, 241, 0.25)',
              padding: 16,
              borderRadius: 16
            }}>
              <div style={{ fontSize: '0.78rem', color: 'var(--text-secondary)', fontWeight: 700, textTransform: 'uppercase' }}>
                Active Travel Corridor
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginTop: 8 }}>
                <span style={{ fontSize: '1.2rem', fontWeight: 800 }}>{pet.originCountry}</span>
                <span style={{ color: 'var(--color-brand-accent)', fontWeight: 800 }}>✈️ ➔</span>
                <span style={{ fontSize: '1.2rem', fontWeight: 800, color: 'var(--color-emerald)' }}>{pet.destinationCountry}</span>
              </div>
            </div>

            {/* Vet of Record */}
            <div style={{
              background: 'var(--bg-surface-elevated)',
              padding: 16,
              borderRadius: 16,
              border: '1px solid var(--border-color)'
            }}>
              <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', fontWeight: 700, textTransform: 'uppercase' }}>
                Attending Licensed Veterinarian
              </div>
              <div style={{ fontWeight: 700, marginTop: 4, color: 'var(--text-primary)' }}>
                {pet.veterinarian?.name || 'Dr. Sarah Jenkins, DVM'}
              </div>
              <div style={{ fontSize: '0.82rem', color: 'var(--text-secondary)' }}>
                {pet.veterinarian?.clinic} • {pet.veterinarian?.phone}
              </div>
            </div>
          </div>

          {/* Column 3: Health Status Badges & Digital QR */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 16, justifyContent: 'between' }}>
            <div style={{
              background: 'var(--bg-surface-elevated)',
              padding: 16,
              borderRadius: 16,
              border: '1px solid var(--border-color)'
            }}>
              <h4 style={{ fontSize: '0.9rem', color: 'var(--text-primary)', marginBottom: 12, display: 'flex', alignItems: 'center', gap: 6 }}>
                <Syringe size={16} color="var(--color-brand-primary)" /> Key Vaccine Compliance
              </h4>
              
              <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <span style={{ fontSize: '0.82rem', color: 'var(--text-secondary)' }}>Rabies Vaccination:</span>
                  {rabiesVaccine && rabiesStatus ? (
                    <span className={`badge badge-${rabiesStatus.status}`}>
                      {rabiesStatus.status.toUpperCase()} ({rabiesVaccine.dateExpires || 'N/A'})
                    </span>
                  ) : (
                    <span className="badge badge-danger">MISSING</span>
                  )}
                </div>

                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <span style={{ fontSize: '0.82rem', color: 'var(--text-secondary)' }}>Rabies Titre (FAVN):</span>
                  {titreTest ? (
                    <span className="badge badge-valid">PASSED ({titreTest.dateExpires})</span>
                  ) : (
                    <span className="badge badge-warning">NOT DRAWN</span>
                  )}
                </div>

                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <span style={{ fontSize: '0.82rem', color: 'var(--text-secondary)' }}>Microchip Scan Date:</span>
                  <span style={{ fontSize: '0.82rem', fontWeight: 700, color: 'var(--text-primary)' }}>
                    {pet.microchipDate}
                  </span>
                </div>
              </div>
            </div>

            {/* QR Code Seal Box */}
            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: 16,
              background: 'rgba(6, 182, 212, 0.08)',
              border: '1px dashed rgba(6, 182, 212, 0.4)',
              padding: 16,
              borderRadius: 16
            }}>
              <div style={{
                width: 60,
                height: 60,
                background: '#fff',
                borderRadius: 8,
                padding: 6,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center'
              }}>
                <QrCode size={48} color="#0F172A" />
              </div>
              <div>
                <div style={{ fontWeight: 700, fontSize: '0.85rem', color: 'var(--color-brand-accent)' }}>
                  Digital Verification Seal
                </div>
                <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginTop: 2 }}>
                  Scan code at customs / border inspection for instant record validation.
                </div>
              </div>
            </div>

            <button 
              onClick={() => onTabChange('checklist')}
              className="btn-secondary" 
              style={{ width: '100%', justifyContent: 'center' }}
            >
              View Pet Travel Readiness Checklist ➔
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
